fixtures:
  repositories:
    stdlib:
      repo: "git://github.com/puppetlabs/puppetlabs-stdlib.git"
      ref: 4.7.0
    sysctl:
      repo: "git://github.com/thias/puppet-sysctl.git"
      ref: 1.0.2
  symlinks:
    swap_file: "#{source_dir}"
